package pkg2024_exam_q2;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

public class MovieTicket_Frame extends javax.swing.JFrame 
{  
    public MovieTicket_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Report = new javax.swing.JTextArea();
        Combox_MovieNames = new javax.swing.JComboBox<>();
        TextField_Price = new javax.swing.JTextField();
        TextField_NumberOfTickets = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu_File = new javax.swing.JMenu();
        JMenuItem_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMenuItem_Process = new javax.swing.JMenuItem();
        JMenuItem_Clear = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MOVIE:");

        jLabel2.setText("NUMBER OF TICKETS:");

        jLabel3.setText("TICKET PRICE:");

        jLabel4.setText("TICKET REPORT:");

        jScrollPane1.setEnabled(false);

        TextArea_Report.setColumns(20);
        TextArea_Report.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextArea_Report.setRows(5);
        jScrollPane1.setViewportView(TextArea_Report);

        Combox_MovieNames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Napoleon", "Oppenheimer", "Damsel" }));

        JMenu_File.setText("File");

        JMenuItem_Exit.setText("Exit");
        JMenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_ExitActionPerformed(evt);
            }
        });
        JMenu_File.add(JMenuItem_Exit);

        jMenuBar1.add(JMenu_File);

        jMenu2.setText("Tools");

        JMenuItem_Process.setText("Process");
        JMenuItem_Process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_ProcessActionPerformed(evt);
            }
        });
        jMenu2.add(JMenuItem_Process);

        JMenuItem_Clear.setText("Clear");
        JMenuItem_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_ClearActionPerformed(evt);
            }
        });
        jMenu2.add(JMenuItem_Clear);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Combox_MovieNames, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextField_Price)
                            .addComponent(TextField_NumberOfTickets))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Combox_MovieNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_NumberOfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TextField_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMenuItem_ExitActionPerformed

    private void JMenuItem_ProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_ProcessActionPerformed
     
     try
     { 
        String movieName = Combox_MovieNames.getSelectedItem().toString();
     
        int numberOfTickets = Integer.parseInt(TextField_NumberOfTickets.getText());

        double price = Double.parseDouble(TextField_Price.getText());
        
        String output = "";
        
        //Create the actual object of MovideTicketData class that holds actual values
        MovieTicketData movieData = new MovieTicketData(movieName, numberOfTickets, price);
        
        //To access the 2 methods to calcualte the totals and validations we need to make instance of the class
        MovieTickets mt = new MovieTickets();
        
        //ValidateData method takes in an object holding values of Movie Tickets
        if(mt.ValidateData(movieData) == true)//if the method returns a true that means the data is valid and we can then calculate the total price
        {
           //We can only calculate the total price if the data is valid
           double totalPrice = mt.CalculateTotalTicketPrice(numberOfTickets, price);
           
           output = "MOVIE NAME: " + movieName + "\n"
            + "MOVIE TICKET PRICE: R" + price + "\n"
            + "NUMBER OF TICKETS: " + numberOfTickets + "\n"
            + "TOTAL TICKET PRICE: R" + totalPrice ;
        }
        
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid input! Check your entries.");
            return; //Ends the programs here does not proceed to write wrong data to the text area or text file
        }

        TextArea_Report.setText(output);

        //Write the same output report to the text file
        FileWriter writer = new FileWriter("report.txt", true);
        
        writer.write("MOVIE TICKET REPORT \n"
                + "*********************************** \n"
                + output + "\n"
                + "**********************************\n");
        writer.close();//Very important
        
        JOptionPane.showMessageDialog(this, "Record saved successfully!");
     }
      catch(IOException e)
      {
         JOptionPane.showMessageDialog(this, "Error saving file: " + e.getMessage());
      }

    }//GEN-LAST:event_JMenuItem_ProcessActionPerformed

    private void JMenuItem_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_ClearActionPerformed
        TextField_NumberOfTickets.setText("");
        TextField_Price.setText("");
        TextArea_Report.setText("");
    }//GEN-LAST:event_JMenuItem_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieTicket_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieTicket_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combox_MovieNames;
    private javax.swing.JMenuItem JMenuItem_Clear;
    private javax.swing.JMenuItem JMenuItem_Exit;
    private javax.swing.JMenuItem JMenuItem_Process;
    private javax.swing.JMenu JMenu_File;
    private javax.swing.JTextArea TextArea_Report;
    private javax.swing.JTextField TextField_NumberOfTickets;
    private javax.swing.JTextField TextField_Price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
